blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('blog/detail/<blog_id>', views.details, name='details'),
    path('blog/pub', views.publish, name='publish'),
    path('blog/comment/pub', views.pub_comment, name='comment'),
    path('search', views.search, name='search')
]

hauth/urls.py
from django.urls import path
from hauth.views import LoginView,RegisterView,LogoutView
from . import views

app_name = 'hauth'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('captcha/',views.send_captcha,name='send_mail'),
    path('logout/',LogoutView.as_view() ,name='logout'),
]

hui_blog/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('blog.urls')),
    path('auth/',include('hauth.urls'))
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}{% endblock %}</title>
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js'%}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'jquery/jquery-3.7.1.min.js'%}"></script>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    
    {% block head %}{% endblock %}
</head>
<body>
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink :href="#bootstrap"></use>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="{% url 'blog:publish' %}" class="nav-link px-2 text-secondary">发布博客</a></li>

            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}" method="get">
                <input type="search" name="q" class="form-control " placeholder="搜索..." aria-label="Search">
            </form>
             {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'image/lena.jpg' %}" alt="mdo" width="32" height="32" class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url 'hauth:logout' %}">退出登录</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="text-end">
                    <a href="{% url 'hauth:login' %}" type="button" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'hauth:register' %}" type="button" class="btn btn-primary">注册</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">

    {% block main %}{% endblock %}
</main>
</body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}

{% block title %}
    博客详情
{% endblock %}

{% block head %}

    <link rel="stylesheet" href="{% static 'highlight/styles/github-dark.min.css' %}">
    <script src="{% static 'highlight/highlight.min.js'  %}"></script>
{% endblock %}

{% block main %}
    <h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static 'image/lena.jpg' %}" alt="" width="30" height="30">
        <span class="ms-2">{{ blog.author.username }}</span>
        <span class="ms-2">于</span>
        <span class="ms-2">{{ blog.pub_time|date:"Y年m月d日 h时i分" }}发布</span>
    </div>
    <hr>
    <div class="py-2">{{ blog.content|safe }}</div>
    <hr>
    <div class="mt-2">
        <h3>评论({{ blog.comments.all|length }})</h3>
        <form action="{% url 'blog:comment' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入你的评论..." name="content">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary ">评论</button>
            </div>
        </form>
    </div>
    <div class="mt-2">
        <ul class="list-group list-group-flush">
            {% for comment in blog.comments.all %}
                <li class="list-group-item">
                  <div class="d-flex justify-content-between text-body-secondary">
                      <div class="user-info">
                          <img src="{% static 'image/lena.jpg' %}" class="rounded-circle" width="40" height="40" alt="">
                          <span class="ms-2">{{ comment.author.username }}</span>
                      </div>
                      <div class="create-time" style="line-height: 40px;">{{ comment.pub_time|date:"Y年m月d日 h时i分" }}</div>
                  </div>
                  <div class="mt-2">{{ comment.content }}</div>
              </li>
            {% endfor %}
        </ul>
    </div>
    <script>
    hljs.highlightAll();
    </script>
{% endblock %}



 

templates/index.html
{% extends 'base.html' %}
{% block title %}首页 {% endblock %}

{% block main %}
    <h1>博客列表</h1>
    <div class="row row-cols-2 row-gap-2">
    {% for blog in blogs %}



        <div class="col">
            {#自动帮忙布局 分两列#}
            <div class="card ">
                <div class="card-header">
                    <a href="{% url 'blog:details' blog_id=blog.id %}">{{ blog.title }}</a>
                </div>
                <div class="card-body" style="height: 125px">

                    <p class="card-text">{{ blog.content|striptags|truncatechars:200 }}</p>

                </div>
                <div class="card-footer text-body-secondary d-flex justify-content-between">
                    <div>
                        <img src="{% static 'image/lena.jpg' %}" class="rounded-circle" alt="avatar" width="30"
                             height="30">
                        {{ blog.author.name }}
                    </div>
                    <div>
                        time: {{ blog.pub_time|date:"Y年m月d日 h时i分" }}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
    登录
{% endblock %}

{% block main %}
	<div class="m-auto" style="max-width: 330px">
            <h1>登录</h1>
            <form action="" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label>用户名:</label>
                    <input type="text" class="form-control" name="username" placeholder="请输入用户名...">
                </div>
                <div class="mb-3">
                    <label>密码:</label>
                    <input type="password" class="form-control" name="password" placeholder="请输入密码...">
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        记住我
                    </label>
                </div>
                <div class="mt-5">
                    <button class="btn btn-primary w-100">立即登录</button>
                </div>

            </form>
        </div>
{% endblock %}
    

templates/pub_blog.html
{% extends 'base.html'%}
{% block head %}
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <!-- 引入 css -->
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <!-- 引入 js -->
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <style>
        #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
{% endblock %}
{% block main %}
	<h1>发布博客</h1>
    <div class="mt-3">
        <form action="" method="post">
         {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">标题</label>
                <input type="text" name="title" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">分类</label>
                <select name="category" class="form-select" id="category-select">
                    {% for category in category_name %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                    
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">内容</label>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-3 text-end">
                <button class="btn  btn-primary" id="submit-btn"> 发布</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}
    注册
{% endblock %}
{% block head %}
    <script src="{% static 'register.js' %}"></script>
{% endblock %}
{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1>注册</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>用户名</label>
                <input type="text" name="username" class="form-control" placeholder="用户名">
            </div>
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>验证码</label>
                <div class="input-group">
                    <input type="text" class="form-control" name="captcha" placeholder="验证码"
                           aria-label="Recipient's username" aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                </div>
            </div>

            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="mb-3">
                <button class="btn btn-primary w-100">立即注册</button>
            </div>
        </form>
    </div>
{% endblock %}